"""sprint3_complaint_resolution_fields

Revision ID: 2d36eb8e82cf
Revises: b3b83487a579
Create Date: 2026-03-12 23:55:52.401754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d36eb8e82cf'
down_revision: Union[str, None] = 'b3b83487a579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('resolved_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('complaints', sa.Column('reopen_reason', sa.String(length=500), nullable=True))
    op.add_column('complaints', sa.Column('is_priority', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'is_priority')
    op.drop_column('complaints', 'reopen_reason')
    op.drop_column('complaints', 'resolved_confirmed_at')
    # ### end Alembic commands ###
