"""initial

Revision ID: 3c19252f762a
Revises: 
Create Date: 2026-02-26 11:43:18.055514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c19252f762a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_reported_issue', sa.String(length=500), nullable=True),
    sa.Column('repaired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mess_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.Enum('chronic', 'spike', name='alerttype'), nullable=False),
    sa.Column('dimension', sa.Enum('food_quality', 'food_quantity', 'hygiene', 'menu_variety', 'timing', name='messdimension'), nullable=False),
    sa.Column('meal', sa.Enum('breakfast', 'lunch', 'dinner', name='mealperiod'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('participation_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('student', 'laundry_man', 'mess_secretary', 'mess_manager', 'assistant_warden', 'warden', 'chief_warden', name='userrole'), nullable=False),
    sa.Column('hostel_mode', sa.Enum('college', 'autonomous', name='hostelmode'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('roll_number', sa.String(length=100), nullable=True),
    sa.Column('erp_document_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sanitized_text', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Enum('mess', 'laundry', 'maintenance', 'interpersonal', 'critical', 'uncategorised', name='complaintcategory'), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='complaintseverity'), nullable=True),
    sa.Column('status', sa.Enum('INTAKE', 'CLASSIFIED', 'AWAITING_APPROVAL', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'REOPENED', 'ESCALATED', name='complaintstatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_suggested_category', sa.Enum('mess', 'laundry', 'maintenance', 'interpersonal', 'critical', 'uncategorised', name='complaintcategory'), nullable=True),
    sa.Column('ai_suggested_assignee', sa.UUID(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('classified_by', sa.Enum('llm', 'fallback', 'manual', name='classifiedby'), nullable=False),
    sa.Column('flagged_input', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Enum('wrong_category', 'wrong_assignee', 'wrong_severity', 'other', name='overridereason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_suggested_assignee'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laundry_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('booked', 'cancelled', 'completed', 'no_show', name='slotstatus'), nullable=False),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('priority_reason', sa.String(length=500), nullable=True),
    sa.Column('priority_approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mess_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('meal', sa.Enum('breakfast', 'lunch', 'dinner', name='mealperiod'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('food_quality', sa.Integer(), nullable=False),
    sa.Column('food_quantity', sa.Integer(), nullable=False),
    sa.Column('hygiene', sa.Integer(), nullable=False),
    sa.Column('menu_variety', sa.Integer(), nullable=False),
    sa.Column('timing', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('complaint_assigned', 'approval_needed', 'mess_alert', 'laundry_reminder', 'machine_down', 'complaint_resolved', 'registration_pending', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('ai_suggested_category', sa.Enum('mess', 'laundry', 'maintenance', 'interpersonal', 'critical', 'uncategorised', name='complaintcategory'), nullable=False),
    sa.Column('ai_suggested_severity', sa.Enum('low', 'medium', 'high', name='complaintseverity'), nullable=False),
    sa.Column('ai_suggested_assignee', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'corrected', name='approvalstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('override_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_suggested_assignee'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('override_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('warden_id', sa.UUID(), nullable=False),
    sa.Column('original_category', sa.Enum('mess', 'laundry', 'maintenance', 'interpersonal', 'critical', 'uncategorised', name='complaintcategory'), nullable=False),
    sa.Column('corrected_category', sa.Enum('mess', 'laundry', 'maintenance', 'interpersonal', 'critical', 'uncategorised', name='complaintcategory'), nullable=False),
    sa.Column('original_severity', sa.Enum('low', 'medium', 'high', name='complaintseverity'), nullable=False),
    sa.Column('corrected_severity', sa.Enum('low', 'medium', 'high', name='complaintseverity'), nullable=False),
    sa.Column('original_assignee', sa.UUID(), nullable=True),
    sa.Column('corrected_assignee', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('wrong_category', 'wrong_assignee', 'wrong_severity', 'other', name='overridereason'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corrected_assignee'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_assignee'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warden_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('override_logs')
    op.drop_table('approval_queue')
    op.drop_table('notifications')
    op.drop_table('mess_feedback')
    op.drop_table('laundry_slots')
    op.drop_table('complaints')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('mess_alerts')
    op.drop_table('machines')
    # ### end Alembic commands ###
