"""add_sprint_6_user_fields

Revision ID: 7f928dfccad1
Revises: 8d59bc56aa84
Create Date: 2026-03-19 01:08:43.360264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f928dfccad1'
down_revision: Union[str, None] = '8d59bc56aa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_rejected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('rejection_reason', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('has_seen_onboarding', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_seen_onboarding')
    op.drop_column('users', 'rejection_reason')
    op.drop_column('users', 'is_rejected')
    # ### end Alembic commands ###
