"""sprint5_hostel_config_refresh_tokens_push_subscriptions

Revision ID: 80db1c48cf9d
Revises: c1cc0caedd71
Create Date: 2026-03-17 12:11:05.848522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80db1c48cf9d'
down_revision: Union[str, None] = 'c1cc0caedd71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostel_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hostel_name', sa.String(length=255), nullable=False),
    sa.Column('hostel_mode', sa.String(length=50), nullable=False),
    sa.Column('total_floors', sa.Integer(), nullable=False),
    sa.Column('total_students_capacity', sa.Integer(), nullable=False),
    sa.Column('complaint_rate_limit', sa.Integer(), nullable=False),
    sa.Column('approval_queue_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('complaint_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('mess_alert_threshold', sa.Float(), nullable=False),
    sa.Column('mess_critical_threshold', sa.Float(), nullable=False),
    sa.Column('mess_min_participation', sa.Float(), nullable=False),
    sa.Column('mess_min_responses', sa.Integer(), nullable=False),
    sa.Column('laundry_slots_start_hour', sa.Integer(), nullable=False),
    sa.Column('laundry_slots_end_hour', sa.Integer(), nullable=False),
    sa.Column('laundry_slot_duration_hours', sa.Integer(), nullable=False),
    sa.Column('laundry_noshow_penalty_hours', sa.Integer(), nullable=False),
    sa.Column('laundry_cancellation_deadline_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_config_id'), 'hostel_config', ['id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=2000), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=100), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.add_column('laundry_slots', sa.Column('no_show_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('laundry_slots', sa.Column('late_cancellation_at', sa.DateTime(timezone=True), nullable=True))
    # Sprint 5: Add 'no_show' to the LaundrySlotStatus PostgreSQL enum
    # Alembic autogenerate does not detect Python Enum changes — raw SQL required.
    op.execute("ALTER TYPE laundryslostatus ADD VALUE IF NOT EXISTS 'no_show'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laundry_slots', 'late_cancellation_at')
    op.drop_column('laundry_slots', 'no_show_at')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_hostel_config_id'), table_name='hostel_config')
    op.drop_table('hostel_config')
    # ### end Alembic commands ###
