"""sprint7b_api_polish_and_features

Revision ID: c57d21acb8ed
Revises: a1b2c3d4e5f6
Create Date: 2026-03-21 14:08:00.577519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c57d21acb8ed'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure mealtype enum exists — safe to run even if it already exists
    op.execute(
        "DO $$ BEGIN "
        "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mealtype') THEN "
        "CREATE TYPE mealtype AS ENUM ('breakfast', 'lunch', 'dinner', 'snacks'); "
        "END IF; "
        "END $$;"
    )

    op.create_table('mess_menu',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostel_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal', postgresql.ENUM('breakfast', 'lunch', 'dinner', 'snacks', name='mealtype', create_type=False), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mess_menu_hostel_id'), 'mess_menu', ['hostel_id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostel_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_hostel_id'), 'notices', ['hostel_id'], unique=False)
    # server_default='0' required so existing rows get the default value
    op.add_column('users', sa.Column('feedback_streak', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('last_feedback_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_feedback_date')
    op.drop_column('users', 'feedback_streak')
    op.drop_index(op.f('ix_notices_hostel_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_mess_menu_hostel_id'), table_name='mess_menu')
    op.drop_table('mess_menu')
    # ### end Alembic commands ###
